name: MLOps Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug File Paths
      run: |
        echo "Current Working Directory:"
        pwd
        echo "List of Files:"
        ls -R

    - name: Run Training and Log to MLflow
      run: |
        python train.py

    - name: Upload Artifacts (Model & Plots)
      uses: actions/upload-artifact@v3
      with:
        name: trained-model-artifacts
        path: /tmp/mlruns
